export const assets = {
  images: {
    // "chisato": "assets/images/chisato.png",
    "chisato.spritesheet": "assets/images/chisato.spritesheet@0.5.json",
    chisato_success: "assets/images/chisato_06@0.5.png",
    chisato_gameover_0: "assets/images/chisato_gameover_0@0.5.png",
    chisato_gameover_1: "assets/images/chisato_gameover_1@0.5.png",
    chisato_gameover_2: "assets/images/chisato_gameover_2@0.5.png",
    chisato_gameover_3: "assets/images/chisato_gameover_3@0.5.png",
    chisato_gameover_4: "assets/images/chisato_gameover_4@0.5.png",
    chisato_gameover_5: "assets/images/chisato_gameover_5@0.5.png",
    chisato_gameover_6: "assets/images/chisato_gameover_6@0.5.png",
    chisato_gameover_7: "assets/images/chisato_gameover_7@0.5.png",
    chisato_gameover_8: "assets/images/chisato_gameover_8@0.5.png",
    chisato_gameover_9: "assets/images/chisato_gameover_9@0.5.png",
    chisato_gameover_10: "assets/images/chisato_gameover_10@0.5.png",
    touch_target_ok_takoyaki_1: "assets/images/touch_target_ok_takoyaki_1.png",
    touch_target_ng_piman_1: "assets/images/touch_target_ng_piman_1.png",
    touch_target_ng_piman_2: "assets/images/touch_target_ng_piman_2.png",
    touch_target_effect_blue: "assets/images/touch_target_effect_blue.png",
    touch_target_effect_green: "assets/images/touch_target_effect_green.png",
    touch_target_effect_orange: "assets/images/touch_target_effect_orange.png",
    touch_target_effect_pink: "assets/images/touch_target_effect_pink.png",
    touch_target_effect_skyblue:
      "assets/images/touch_target_effect_skyblue.png",
  },
  sounds: {
    shan: "assets/sounds/shan.wav",
    pon: "assets/sounds/pon.mp3",
    drum_loop: "assets/sounds/drum_loop.wav",
  },
};
