# secrets.GCP_SERVICE_ACCOUNT_KEY_DEV
# sokontokoro-factory-develop-65bafa735fc5_ci-account.json
#
# secrets.FIREBASE_TOKEN
# $ firebase login:ci
#

name: ci-develop

on:
  push:
    branches:
      - develop
      - develop-**

  schedule:
    - cron: "0 9 * * 1"

env:
  NODE_VERSION: 12

jobs:
  install:
    runs-on: macos-latest
    steps:
      # checkout
      - uses: actions/checkout@v2
      # setup env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm@latest
      # install deps
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install

  build-and-deploy-portal:
    runs-on: macos-latest
    needs: install
    steps:
      # checkout
      - uses: actions/checkout@v2
      # setup env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm@latest
      # install deps
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      # build
      - run: npm -w portal run build-dev
      # deploy
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}
          export_default_credentials: true
      - run: npm -w portal run deploy-dev
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/develop-portal'

  build-and-deploy-firebase:
    runs-on: macos-latest
    needs: install
    steps:
      # checkout
      - uses: actions/checkout@v2
      # setup env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm@latest
      # install deps
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      # build
      - run: npm -w @sokontokoro/mikan run build
      - run: npm -w firebase           run build-dev
      # deploy
      - run: npm -w firebase           run deploy-dev -- --token ${{ secrets.FIREBASE_TOKEN }}
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/develop-firebase'

  build-and-deploy-games:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        game:
          - honocar
          - shakarin
          - maruten
          - yamidori
          - oimo-no-mikiri
          - rinadoko
          - marusuki
    needs: install
    steps:
      # checkout
      # lfs cache hack: https://github.com/actions/checkout/issues/165#issuecomment-657673315
      - uses: actions/checkout@v2
      - run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      - uses: actions/cache@v2
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
      - run: git lfs pull
      # setup env
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install -g npm@latest
      # install deps
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      # build
      - run: npm -w @sokontokoro/mikan run build
      - run: npm -w ${{ matrix.game }} run build-dev
      # deploy
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}
          export_default_credentials: true
      - run: npm -w ${{ matrix.game }} run deploy-dev
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/develop-${{ matrix.game }}'

  notify:
    runs-on: macos-latest
    needs:
      - build-and-deploy-portal
      - build-and-deploy-firebase
      - build-and-deploy-games
    if: always()
    steps:
      # https://github.com/technote-space/workflow-conclusion-action
      - uses: technote-space/workflow-conclusion-action@v2
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
