name: ci

on:
  push:
    branches:
      - master
      - develop
      - develop-**

  schedule:
    - cron: "0 9 * * *"

env:
  NODE_VERSION: 8.x

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: "Get yarn cache directory path"
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "Restore yarn cache"
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install

  build-and-deploy:
    runs-on: macos-latest
    needs: setup
    strategy:
      matrix:
        app:
          - "honocar"
          - "shakarin"
          - "maruten"
          - "oimo-no-mikiri"
          - "rinadoko"
          - "firebase"
          - "ranking"
    if: ${{
      github.ref == 'refs/heads/master' ||
      github.ref == 'refs/heads/develop' ||
      github.ref == 'refs/heads/develop-${{ matrix.app }}'
      }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      # https://github.com/actions/cache/blob/main/examples.md#node---yarn
      - name: "Get yarn cache directory path"
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: "Restore yarn cache"
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install

      # todo: reuse as artifacts
      - run: yarn workspace @sokontokoro/mikan build
      - run: yarn workspace ${{ matrix.app }} build:dev

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}
          export_default_credentials: true

      - name: Deploy to dev
        if: ${{ github.event_name == 'push' }}
        run: yarn workspace ${{ matrix.app }} deploy:dev
